"""sprint 4: chunk embedding column

Revision ID: 6e794aadf57f
Revises: 7b65c3a40306
Create Date: 2026-09-06 02:52:03.300335

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '6e794aadf57f'
down_revision: str | Sequence[str] | None = '7b65c3a40306'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_column('embedding')

    # ### end Alembic commands ###
