"""sprint 3: chunks table

Revision ID: 7b65c3a40306
Revises: 6bcaf2beb4cc
Create Date: 2026-09-06 02:00:39.441098

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7b65c3a40306'
down_revision: str | Sequence[str] | None = '6bcaf2beb4cc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('chunk_id', sa.String(length=32), nullable=False),
    sa.Column('repository', sa.String(length=255), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=24), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('symbol', sa.String(length=512), nullable=True),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('parent_chunk_id', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('reference_paths', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('chunk_id'),
    sa.UniqueConstraint('repository', 'commit_sha', 'chunk_id', name='uq_chunk_identity')
    )
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chunks_commit_sha'), ['commit_sha'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_repository'), ['repository'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chunks_repository'))
        batch_op.drop_index(batch_op.f('ix_chunks_path'))
        batch_op.drop_index(batch_op.f('ix_chunks_commit_sha'))

    op.drop_table('chunks')
    # ### end Alembic commands ###
