"""sprint 7: human decisions table

Revision ID: 9d61abe6d02a
Revises: 6e794aadf57f
Create Date: 2026-09-12 18:30:26.571290

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '9d61abe6d02a'
down_revision: str | Sequence[str] | None = '6e794aadf57f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('reviewer', sa.String(length=255), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'seq', name='uq_humandecision_run_seq')
    )
    with op.batch_alter_table('human_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_human_decisions_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_human_decisions_run_id'))

    op.drop_table('human_decisions')
    # ### end Alembic commands ###
