"""sprint 9: per-user accounts

Revision ID: e76ae6980d6e
Revises: 9d61abe6d02a
Create Date: 2026-10-03 16:44:03.973060

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e76ae6980d6e"
down_revision: str | Sequence[str] | None = "9d61abe6d02a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("api_key_hash", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("disabled_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("username"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_api_key_hash"), ["api_key_hash"], unique=True)

    with op.batch_alter_table("human_decisions", schema=None) as batch_op:
        # server_default required: existing rows (real deployments with real
        # history) need a concrete value for a new NOT NULL column, not just
        # the ORM-level default (which only applies to rows written *after*
        # this migration). False is simply true for every pre-existing row —
        # none of them were ever verified against a real per-user account.
        batch_op.add_column(
            sa.Column("authenticated", sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("human_decisions", schema=None) as batch_op:
        batch_op.drop_column("authenticated")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_api_key_hash"))

    op.drop_table("users")
    # ### end Alembic commands ###
